name: CI Pipeline Push

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      NODE_ENV: "production"
      V_DOCKER_API: "1.41"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build image
      uses: docker/build-push-action@v4
      with:
        push: false
        context: ./micro-portainer
        tags: |
          docker.io/juliocesarmidia/micro-portainer:latest

  test:
    name: Test Image
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/juliocesarmidia/micro-portainer:latest'
        scan-type: 'image'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL'

  push:
    name: Push Image
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          docker.io/juliocesarmidia/micro-portainer:latest
        tags: |
          type=sha
    - id: setShortSha
      name: Set short SHA
      run: echo "SHA_SHORT=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT
    - name: Login to Docker Hub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Push image
      uses: docker/build-push-action@v4
      with:
        push: ${{ github.event_name != 'pull_request' }}
        context: ./micro-portainer
        tags: |
          docker.io/juliocesarmidia/micro-portainer:latest
          docker.io/juliocesarmidia/micro-portainer:${{ steps.setShortSha.outputs.SHA_SHORT }}
          ghcr.io/juliocesarscheidt/micro-portainer:latest
          ghcr.io/juliocesarscheidt/micro-portainer:${{ steps.setShortSha.outputs.SHA_SHORT }}
        labels: ${{ steps.meta.outputs.labels }}
