name: CI Pipeline Push

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      NODE_ENV: "production"
      V_DOCKER_API: "1.41"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        context: ./micro-portainer
        tags: |
          docker.io/juliocesarmidia/micro-portainer:latest
          docker.io/juliocesarmidia/micro-portainer:${{ github.sha }}
          ghcr.io/juliocesarscheidt/micro-portainer:latest
          ghcr.io/juliocesarscheidt/micro-portainer:${{ github.sha }}
